### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by UziTech**
- Update all dependencies including replacing `istanbul` with `nyc`
- Remove `makefile` and other unnecessary files
- Add `package-lock.json` (Not sure if you wanted to commit this, or I could add it to `.gitignore`)

### CODE REVIEW

**Comment by jsumners** [comment]
Actually, I'd rather have `package-lock.json` added to the `.gitignore`. It offers no benefit to libraries. `npm install` doesn't even consider it when performing an install.

**Comment by UziTech** [comment]
> It offers no benefit to libraries.

I think the point of it is so the development team always has the same version of deps installed. If I have an issue because of a dependency it will be easier for you to reproduce it with the exact same dependencies. But you are right limited benefit especially with a small team.

**Review by jsumners — APPROVED** [review]
LGTM

FYI, this is the argument I go to on the lock files whenever the issue comes up -- https://github.com/sindresorhus/ama/issues/479#issuecomment-310661514

**Comment by UziTech** [comment]
Ya here is the argument for having them: https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

I don't think a small library would see any benefit for having one especially if it is not usually a devdependency. I also don't think anyone is running `npm install` every time one of their dependencies gets an update to "match the dependency tree of users".

Seems like 6 on one side half dozen on the other.

**Pull request merged**
